WHITESPACE = _{ " " }
COMMENT    = _{ "/*" ~ (!"*/" ~ ANY)* ~ "*/" }

identifier = { XID_CONTINUE+ }

enum_value      = { identifier ~ ("|" ~ identifier)* }
enum_definition = { identifier ~ "=" ~ enum_value }

int_value      = { NUMBER+ }
int_definition = { identifier ~ "=" ~ int_value }

definition  = { int_definition | enum_definition }
definitions = { SOI ~ NEWLINE* ~ definition? ~ (NEWLINE+ ~ definition)* ~ NEWLINE* ~ EOI }
