WHITESPACE = _{ " " }
COMMENT    = _{ "/*" ~ (!"*/" ~ ANY)* ~ "*/" }

identifier = { XID_CONTINUE+ }

enum_type       = { identifier ~ ("|" ~ identifier)* }
enum_definition = { identifier ~ ":" ~ enum_type ~ "=" ~ identifier }

int_value      = { NUMBER+ }
int_definition = { identifier ~ "=" ~ int_value }

definition  = { int_definition | enum_definition }
definitions = { SOI ~ NEWLINE* ~ definition? ~ (NEWLINE+ ~ definition)* ~ NEWLINE* ~ EOI }
