[package]
name = "gossip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.4.0"
pest = "2.7.4"
pest_derive = "2.7.4"
heck = "0.4.1"
csv = "1.3.0"
